apiVersion: apps/v1
kind: Deployment
metadata:
  name: p8e-webservice-deployment
  labels:
    app: p8e-webservice
spec:
  selector:
    matchLabels:
      app: p8e-webservice
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: p8e-webservice
    spec:
      containers:
      - name: p8e-webservice
        image: ghcr.io/provenance-io/p8e-api-webservice:0.7.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common
        - configMapRef:
            name: p8e-webservice